export const artifacts = [
  // THEME 1: Intentional Exploration
  {
    id: "first-job",
    title: "My First Job",
    date: "September 2023",
    period: "Sophomore Year, Fall Quarter",
    theme: "Intentional Exploration",
    themeKey: "exploration",
    year: 2023,
    reflection: "Being somebody who has always craved new opportunities, experiences, and connections, I was super excited when I discovered the UW HFS student job website. The idea of having a little extra money every month to spend on sidequests sounded like an incredibly lucrative offer. So, I took a leap of faith and put together a very simple resume. This resume was truly reflective of everything I had been up to in freshman year, and it almost seemed like a moment of true adulting to me at that moment in time. After building my resume, I perused the student job website to apply for positions that I'd be eligible for. In this list, I came across the job of HR Student Assistant. This was a desk job that sort of related to my business degree, and I was excited about the possibility of learning more about how recruiting works. Mustering up courage, I hit apply, and a few weeks and an interview later, I had secured myself a job starting in my sophomore fall. When my first paycheck hit my bank account, I was elated. My happiness came not from knowing that I could buy more things for myself, but from the idea that I could buy my parents a gift with money I earned myself. This was an impactful moment in my life because it taught me the importance of earning and managing money. Working my first job in an office environment also gave me a new sense of independence that I had not experienced before, and an early peek into corporate culture.",
    photo: "/images/artifacts/first-job.webp",
  },
  {
    id: "startup-world",
    title: "Startup World and Networking",
    date: "September 2024 – June 2025",
    period: "Junior Year",
    theme: "Intentional Exploration",
    themeKey: "exploration",
    year: 2024,
    reflection: "In my sophomore year, I applied to the Lavin Entrepreneurship program to explore my interest in the field. Spending my first year in the program, I learned a lot about startups, building connections, meeting a lot of cool people, and exploring a startup idea concept in a classroom setting. This first-year experience was enough to motivate me to apply for a leadership position with the program. Amongst the various positions available on the team, spanning from administrative to marketing, I interviewed for the director of outreach role. My desire to pursue this role stemmed from my priority of developing a network of connections in the Seattle startup community. From organizing speaker events to cold emailing startup founders, this role pushed me to intentionally seek out connection opportunities that would not come naturally. During my time in this role, I faced quite a few challenges, including differences of opinion with the other leaders, time management, and communicating task distribution. While I initially struggled to fit in with the leadership team due to creative differences and leadership style, I eventually found a way to communicate and understand the requirements of the tasks at hand effectively. This role taught me that leadership necessitates not just active listening but also emotional agility. The best part of this experience for me was getting to meet the founders who came from similar backgrounds and shared my passion for unstructured problem-solving. This role became a source of continuous inspiration for me due to the people I crossed paths with on a regular basis.",
    photo: "/images/artifacts/startup-world.webp",
  },
  {
    id: "bmcc",
    title: "BMCC",
    date: "November 10–17, 2024",
    period: "Junior Year, Fall Quarter",
    theme: "Intentional Exploration",
    themeKey: "exploration",
    year: 2024,
    reflection: "Business case competitions have been a very constant part of my academic journey at UW. These are experiences that I have purposefully undertaken to feed my curiosity and collect more skills to enhance my problem-solving mindset. Countless practices, all-nighters, slide decks, and research sessions led me to be selected for my second international case competition at the Universidad Panamericana, Guadalajara. While I was incredibly excited and grateful to have the opportunity to represent UW again at the international stage, I was also concerned about having to build a team dynamic with three new teammates whom I had previously never worked with. Through practice cases, group dinners, and fun team bonding activities over the three-month preparation period, I was able to establish a foundation of trust among the team. However, this foundation could not be tested until we were under the pressure of the 24-hour case challenge at the actual competition. Working through the nerves, beating groupthink, and maximizing our problem-solving set, my team and I came up with a solution that we were proud to present. This was a solution that reflected a holistic team perspective, and it was culturally resonant. While this solution did not lead us to becoming the winning team, it was a testament to our bonding as a team and our ability to come up with a feasible and implementable solution under time constraints. I found incredible satisfaction in returning from Mexico, not with a win but with a lot of beautiful experiences, a refreshed perspective, and teammates who are now my close friends.",
    photo: "/images/artifacts/bmcc.webp",
  },
  {
    id: "first-c2-event",
    title: "First C2 Event",
    date: "January 21, 2025",
    period: "Junior Year, Winter Quarter",
    theme: "Intentional Exploration",
    themeKey: "exploration",
    year: 2025,
    reflection: "Sitting in my dorm building lobby during the Spring quarter of sophomore year, three of my friends who also happened to be my case teammates got into a long, late-night discussion about resources and succeeding in the case competition space. This was a reflective conversation because we were the team that had slowly built up our familiarity with case competitions in a trial-and-error manner. We talked about how it would be incredible to have a student organization that could teach students how to approach case competitions, what they entail, and the skills needed to succeed. From a late-night dorm conversation to various brainstorming and planning sessions over the summer and fall, our team was able to finally register and start this organization, the UW Case Club, which was a rough idea a few months ago. From administrative tasks to marketing materials to skill resources, we deliberated the logistics of the club for hours. We did not just want to create a club that taught skills in a peer-to-peer learning environment, but rather we wanted this to be a space where students could find friends and teammates. We ran our first event to explain the basics of case competitions and the vision of our club. Seeing the room our team booked for the event full, I felt assured and grateful that we were taking strides in the right direction. This moment was also special because it marked my transition from being just a competitor to a mentor for a skill that I had acquired over my time at UW, and this made it even more heartwarming.",
    photo: "/images/artifacts/first-c2-event.webp",
  },
  {
    id: "writing-not-competing",
    title: "Writing, Not Competing?",
    date: "February 2025",
    period: "Junior Year, Winter Quarter",
    theme: "Intentional Exploration",
    themeKey: "exploration",
    year: 2025,
    reflection: "My journey of involvement at the Foster School of Business has been a full circle because I have embodied the role of a student, mentor, leader, and TA all over the course of these four beautiful years. Another role to this list was added when I was offered the opportunity to write a diversity-focused case for a case competition hosted by the Undergraduate Women in Business club. This opportunity was both exciting and scary for me. It was exciting because I would get to explore casing from across the table, and scary because this was uncharted territory for me. At first, when I was offered the opportunity, I went into an overthinking spiral on how I was not qualified enough to write a case that other students would use to compete. However, my co-case writer and friend helped me overcome this dilemma and take it on as a challenge. From countless research sessions to re-reading each section for diction choice, I realized that there is a lot more to the skills acquired through case competitions than just being able to produce a clear and implementable solution to a problem. The way a case is written, framed, and presented has a meaningful impact on the way it is perceived by the competitor. Going through this writing experience helped me become a better competitor as well because I was able to decode the implicit asks of a case much better.",
    photo: "/images/artifacts/writing-not-competing.webp",
  },
  // THEME 2: Consistent Curiosity
  {
    id: "always-loved-dancing",
    title: "She Has Always Loved Dancing",
    date: "September 2023 – June 2024",
    period: "Sophomore Year",
    theme: "Consistent Curiosity",
    themeKey: "curiosity",
    year: 2023,
    reflection: "Dancing has always been one of my favorite hobbies. Ever since I was four years old, I was in some kind of dance class or learning a new choreography tutorial on YouTube. I find dancing to be an incredible stress buster, and it helps me feel grounded in the moment. So, I was elated when I discovered that there was a salsa club event for Dawg Daze during my first week at UW. Warm people and a new dance form were all I needed to find my community and comfort zone at UW. My chance attendance of this Dawg Daze event led me to discovering one of my favorite communities on campus, where I felt seen, heard, and supported. From becoming a club officer in my freshman year to the co-president in my sophomore year, the salsa club was a place where I went to feel the joy of dancing and also share it with others. Being involved in the club taught me how to be a good leader because I really looked up to the president of the club during my first year. She had this distinct aura about her that really brightened up the practice room when she walked, and I, too, wanted to be someone who would put a smile on other people's faces. Throughout my tenure as the club's president, I tried to encourage people to try new moves, make friends, and just feel very connected to the community. In the process of learning the dance and leading the club, I was able to organically learn more about the Latino culture and immerse myself through the creative outlet of dance and music.",
    photo: "/images/artifacts/always-loved-dancing.webp",
  },
  {
    id: "deep-conversations",
    title: "Deep Conversations with Strangers",
    date: "November 17, 2023",
    period: "Sophomore Year",
    theme: "Consistent Curiosity",
    themeKey: "curiosity",
    year: 2023,
    reflection: "After being admitted to the Lavin Entrepreneurship Program, I was enthusiastic to get to know my cohort and engage in intellectually stimulating conversations with like-minded peers. This opportunity came to me in the form of the Lavin retreat. Making my way to the Pack Forest with the cohort, I was curious to see how my interests align and intersect with the people in the program. Even though I was excited, I thought we would be scratching the surface and barely introducing ourselves. However, I was pleasantly surprised when introductions turned into a six-hour-long conversation about our ideas, motivations, and ideologies. Never before had I felt so comfortable sharing my train of thought with individuals I had just met, and to observe that we shared so many lived experiences was heartwarming. To me, a conversation works well when I am being intentional about listening but also participating in the conversation by prompting with guiding questions, and this was one such scenario. I was really touched by how reciprocal each member of the conversation was, and how genuinely interested they were in getting to know each other. A big part of entrepreneurship is being able to find the right people to build a team with who share your passion and vision. This retreat reassured me that my interest in entrepreneurship is unwavering and there is a bright possibility that I might find my co-founders from within this community. While I did not leave this trip with a new startup idea, I did gain a lot of knowledge about my peers and how their perspectives have been shaped by their lived experiences.",
    photo: "/images/artifacts/deep-conversations.webp",
  },
  {
    id: "open-endings",
    title: "Open Endings",
    date: "April 7–12, 2025",
    period: "Junior Year",
    theme: "Consistent Curiosity",
    themeKey: "curiosity",
    year: 2025,
    reflection: "Global Business Case Competition (GBCC) is the UW-hosted International case competition that hosts teams from around the world for a week of casing, exploring, and making connections. When I learned that the applications for the leadership team opened, I immediately started working on it. To me, this was the perfect opportunity to meet fellow competitors from around the world, but also to work in a managerial role to help them have an unforgettable experience. I applied for the role of Ambassador Co-Manager. This role entailed interviewing, recruiting, and training a team of 24 ambassadors that will then become liaisons for the 12 international teams. A big part of my job was to help create an environment where the competitors feel supported and welcome. As a competitor myself, I tried to bring in my personal experience to ensure that we created a magical experience for the teams. The best part of the experience for me included the 6 months of planning leading up to the competition week, and seeing all the planning come to fruition in the form of compliments from competitors and seeing budding connections across the room. Being in this role, I learned a lot because I was going through a huge family emergency right before the kick-off of the competition week. I had to make a decision between being at home and supporting my family, and being at school to support the week of competition. While immensely difficult, I first dealt with my family emergency and then made it back in time to execute my duties over the full competition week. This was one of the most difficult things I had to do during my time at UW, but I am glad I was able to balance my responsibilities and be a part of this incredible experience.",
    photo: "/images/artifacts/open-endings.webp",
  },
  {
    id: "being-a-ta",
    title: "Being a TA",
    date: "January 2025 – June 2026",
    period: "Junior and Senior Year",
    theme: "Consistent Curiosity",
    themeKey: "curiosity",
    year: 2025,
    reflection: "With my curiosity for acquiring new skills, I was thrilled when my friend, who was graduating, asked me to step into her role as a TA for MKTG 305. First, it was heartwarming to know that an upperclassman I looked up to considered me worthy of being able to follow in her footsteps. Second, I was delighted at the opportunity of being able to see the teaching side of a college course. Third, I was going to work for a professor whom I had built up a reputation with, starting in my freshman year, and I really admired her work ethic. In my first quarter on the job, I was nervous because I wanted to be an adequate bridge between the students and the professor. Learning skills like clarifying topics for students, setting up the Canvas page, and writing and grading assignments, I feel very satisfied with the new experiences and questions I encounter in this role. By understanding the teaching team's mentality when writing and grading exams and learning from the lecture content myself, I think this experience has helped me become a better student and learner. Conducting office hours and helping resolve other students' queries has helped me unlearn the habit of not asking for help myself. This has been a welcome change because it has allowed me to improve my productivity and time management skills.",
    photo: "/images/artifacts/being-a-ta.webp",
  },
  {
    id: "passion-in-project",
    title: "Passion in Project",
    date: "Winter 2026",
    period: "Senior Year",
    theme: "Consistent Curiosity",
    themeKey: "curiosity",
    year: 2026,
    reflection: "My college journey has been a lot about wants and shoulds, and realizing the need to strike the right balance between the two. So, when I see the potential of bringing the two together, I am intrigued. In my IS 451 class on business analytics, I discovered that the culminating group project class involves performing data analysis on any topic and being able to answer a key question. The thought of data analytics immediately led me to think about Formula One. Formula One is a racing sport that incorporates a lot of data analysis, specifically related to the car and driver performance. This is a sport that I am passionate about, and the thought of completing a data analysis project on a Formula 1 dataset had my train of thought running around all the different things I can do with this project. From picking the perfect dataset to custom designing a template of the slides, I was super involved every step of the way. Having a topic that I am passionate about, becoming a project was a highly rewarding experience. I was able to see a new side of the sport and develop an appreciation for the level of detail and precision that goes into analyzing driver performance from every team. On the other hand, I was also able to marvel at the ability of data science to spot and explain so many patterns in raw data that would otherwise not be obvious in its original form. The intersection of education and passion is what made this project so special to me, and it has inspired me to take on more passion projects such as this.",
    photo: "/images/artifacts/passion-in-project.webp",
  },
  // THEME 3: Relearning Authenticity
  {
    id: "lifes-philosophy",
    title: "Writing My Life's Philosophy at 18",
    date: "Winter 2023",
    period: "Freshman Year",
    theme: "Relearning Authenticity",
    themeKey: "authenticity",
    year: 2023,
    reflection: "During my first year at UW in the peak winter quarter, I did not expect to be hit with a final assignment that would leave me stunned. I was stunned not because of how difficult the assignment was, but because it required scratching beyond the surface and reflecting on who I really was. As an 18-year-old in my first honors class at UW, I wasn't really expecting to learn the philosophies of Kant and Plato in a class titled \"Disenchantment of the West.\" Throughout this course, I went into lectures with a certain perception of the world and walked out having unlocked another dimension. This was because I was being exposed to ideologies that I had only heard of, but in this course, I was questioning them and wrapping my head around concepts that stuck with me. The culmination of a 5000-word paper on the philosophy of my life was daunting. Never before in my life had I felt nearly threatened by an assignment, and I think this came from the unknowns of what I will end up with as the final product. In the process of writing this paper, I think I subconsciously and consciously examined all of my lived experiences, and deciphered which ones left the most lasting impact on my being. Furthermore, I think I have introspected a lot on my principles and moral compass in the process of writing. My big takeaway from writing this paper was that I owed a lot of my moral compass to a combination of my upbringing and religion. This gave me a lot of clarity in understanding the decisions that I make and why I make them.",
    photo: "/images/artifacts/lifes-philosophy.webp",
  },
  {
    id: "shrm",
    title: "SHRM",
    date: "Spring 2023",
    period: "Freshman Year",
    theme: "Relearning Authenticity",
    themeKey: "authenticity",
    year: 2023,
    reflection: "In the spring quarter of my freshman year, a classmate from my freshman direct seminar reached out to me, asking whether I would be willing to participate in a business case competition. Due to limited exposure to the concept, he explained it to me as a problem-solving activity in a group setting with the opportunity of presenting to a panel of corporate judges. Hearing this explanation, I was immediately interested and committed two hours on a Friday for this competition. The version of me that went into the competition clueless yet open to learning new things was not the same version that came out of the competition. This experience was the beginning of something that became a key theme throughout my undergraduate experience at UW. The adrenaline of coming up with a solution under time pressure, presenting it to a group of judges, and being able to defend it without having evidentiary support really helped me reconnect with the part of my personality that thrives in challenges. What started as a fun problem-solving experience on a random Friday in freshman year built itself into a passion where I took on the roles of an International competitor, mentor, leader, and case writer in my time at UW.",
    photo: "/images/artifacts/shrm.webp",
  },
  {
    id: "caseit-2024",
    title: "CaseIT 2024",
    date: "Winter 2024",
    period: "Sophomore Year",
    theme: "Relearning Authenticity",
    themeKey: "authenticity",
    year: 2024,
    reflection: "At my first ever international case competition, our team's host said to our team, \"An underdog is a hungry dog and a hungry dog runs the fastest.\" This statement especially ran true when, at the end of a week-long competition, we stood tall as second-place winners among fifteen global teams. Having the opportunity to represent UW as a sophomore at Simon Fraser University was truly a moment of pride for me. Being a super competitive person, I have always strived for excellence in every endeavour I undertake. However, going into this competition, I felt a little inferiority complex. Our team comprised some of the youngest competitors, and our experience with information systems was limited, which made me feel inadequate in our ability to devise a practical solution. I think it was this pressure of having limited experience, coupled with my high ambition, that pushed us to devise a solution that we stress-tested in multiple scenarios and backed up with excessive research. It was the motivation from the slight pressure to do UW proud that led us to maximize our potential as a team to produce a solution that was complimented by the judges as \"freakishly good.\" The moment we collected our trophy as a team, I recall that as one of the highlights of my UW journey.",
    photo: "/images/artifacts/caseit-2024.webp",
  },
  {
    id: "lakeside-speaker",
    title: "Going Back to Lakeside as a Guest Speaker",
    date: "Summer 2025",
    period: "Junior Year",
    theme: "Relearning Authenticity",
    themeKey: "authenticity",
    year: 2025,
    reflection: "During the summer before my senior year, I saw an unexpected email pop up in my inbox. It was from the alumni coordinator of my high school, inviting me to be a speaker on a college-ready panel for current students at my high school. I distinctly remember feeling very moved by this, and I immediately said yes to joining the panel. On the day of the actual panel, I felt a sense of comfort in returning to my school as an alumnus who had meaningful experiences and stories to share with current students. I only spent two years studying at my high school, and during those two years, I was so focused on my academics and making the move to a different country worth my while that I lost a part of who I was in the process. However, returning to the school as a speaker with a newfound sense of self and a confidence that I didn't previously show was very empowering. It was comforting to find belonging at my high school after I had already graduated from there. This experience, in a way, helped me undo the regret of not completely expressing myself when I attended high school.",
    photo: "/images/artifacts/lakeside-speaker.webp",
  },
  {
    id: "first-solo-trip",
    title: "First Solo Trip",
    date: "Summer 2025",
    period: "Junior Year",
    theme: "Relearning Authenticity",
    themeKey: "authenticity",
    year: 2025,
    reflection: "During the summer before my senior year, I had the opportunity to take my first solo trip. I planned this trip to Japan because I had completed an internship and language exchange in Kobe, Japan, the previous year, and I had fallen in love with the country. My trip was primarily centered around attending the EXPO 2025 taking place in Osaka, Japan. This was a time when I was looking for motivation and new ideas, and I think traveling helps me discover more about the world and myself. While my intent for this trip was to discover sides of Japan that I wasn't able to experience during my study abroad experience, it ended up being a lesson in independence and in refreshing my perspective towards life. From booking flights and hotels to navigating the subway, I found a new side to myself in the process of exploring. While I have always been fond of traveling and experiencing new things, I never thought that I had the self-drive to be able to explore two cities from a non-traditional lens. I think my attempt to explore was also reflective of my quest to add new knowledge to my train of thought. This trip helped me meet a very independent and self-assured version of myself, and I can't wait to go on more solo trips!",
    photo: "/images/artifacts/first-solo-trip.jpg",
  },
  {
    id: "husky-100",
    title: "Husky 100 Application",
    date: "Winter 2026",
    period: "Senior Year",
    theme: "Relearning Authenticity",
    themeKey: "authenticity",
    year: 2026,
    reflection: "This past winter quarter, I applied for the Husky 100 award. My motivation to apply came from my desire to look back at all the things I had accomplished in my UW journey and to see whether it aligned with what I had envisioned it would be like. For my application, I picked the video medium to share my stories, and I framed my experience in the form of critical moments that have shaped my time here. While I did not get picked for the award, this process made me realize all the things I had been a part of, all the leadership roles that I took on, and all the experiences that make my time here incredibly meaningful. Working through the Husky 100 application made me realize that I had earned amazing connections and experiences at UW that I will cherish forever, and it is these experiences that have changed my life for the better.",
    photo: "/images/artifacts/husky-100.webp",
  },
];
