export const artifacts = [
  // THEME 1: Intentional Exploration
  {
    id: "first-job",
    title: "My First Job",
    date: "September 2023",
    period: "Sophomore Year, Fall Quarter",
    theme: "Intentional Exploration",
    themeKey: "exploration",
    year: 2023,
    reflection: "Being somebody who has always craved new opportunities, experiences, and connections, I was super excited when I discovered the UW HFS student job website. The idea of having a little extra money every month to spend on sidequests sounded like an incredibly lucrative offer. So, I took a leap of faith and put together a very simple resume. This resume was truly reflective of everything I had been up to in freshman year, and it almost seemed like a moment of true adulting to me at that moment in time. After building my resume, I perused the student job website to apply for positions that I'd be eligible for. In this list, I came across the job of HR Student Assistant. This was a desk job that sort of related to my business degree, and I was excited about the possibility of learning more about how recruiting works. Mustering up courage, I hit apply, and a few weeks and an interview later, I had secured myself a job starting in my sophomore fall. When my first paycheck hit my bank account, I was elated. My happiness came not from knowing that I could buy more things for myself, but from the idea that I could buy my parents a gift with money I earned myself. This was an impactful moment in my life because it taught me the importance of earning and managing money. Working my first job in an office environment also gave me a new sense of independence that I had not experienced before, and an early peek into corporate culture.",
    photo: "/images/artifacts/first-job.jpg",
  },
  {
    id: "startup-world",
    title: "Startup World and Networking",
    date: "September 2024 – June 2025",
    period: "Junior Year",
    theme: "Intentional Exploration",
    themeKey: "exploration",
    year: 2024,
    reflection: "In my sophomore year, I applied to the Lavin Entrepreneurship program to explore my interest in the field. Spending my first year in the program, I learned a lot about startups, building connections, meeting a lot of cool people, and exploring a startup idea concept in a classroom setting. This first-year experience was enough to motivate me to apply for a leadership position with the program. Amongst the various positions available on the team, spanning from administrative to marketing, I interviewed for the director of outreach role. My desire to pursue this role stemmed from my priority of developing a network of connections in the Seattle startup community. From organizing speaker events to cold emailing startup founders, this role pushed me to intentionally seek out connection opportunities that would not come naturally. During my time in this role, I faced quite a few challenges, including differences of opinion with the other leaders, time management, and communicating task distribution. While I initially struggled to fit in with the leadership team due to creative differences and leadership style, I eventually found a way to communicate and understand the requirements of the tasks at hand effectively. This role taught me that leadership necessitates not just active listening but also emotional agility. The best part of this experience for me was getting to meet the founders who came from similar backgrounds and shared my passion for unstructured problem-solving. This role became a source of continuous inspiration for me due to the people I crossed paths with on a regular basis.",
    photo: "/images/artifacts/startup-world.jpg",
  },
  {
    id: "bmcc",
    title: "BMCC",
    date: "November 10–17, 2024",
    period: "Junior Year, Fall Quarter",
    theme: "Intentional Exploration",
    themeKey: "exploration",
    year: 2024,
    reflection: null,
    photo: "/images/artifacts/bmcc.jpg",
  },
  {
    id: "first-c2-event",
    title: "First C2 Event",
    date: "January 21, 2025",
    period: "Junior Year, Winter Quarter",
    theme: "Intentional Exploration",
    themeKey: "exploration",
    year: 2025,
    reflection: null,
    photo: "/images/artifacts/first-c2-event.jpg",
  },
  {
    id: "writing-not-competing",
    title: "Writing, Not Competing?",
    date: "February 2025",
    period: "Junior Year, Winter Quarter",
    theme: "Intentional Exploration",
    themeKey: "exploration",
    year: 2025,
    reflection: null,
    photo: "/images/artifacts/lifes-philosophy.jpg",
  },
  // THEME 2: Consistent Curiosity
  {
    id: "always-loved-dancing",
    title: "She Has Always Loved Dancing",
    date: "September 2023 – June 2024",
    period: "Sophomore Year",
    theme: "Consistent Curiosity",
    themeKey: "curiosity",
    year: 2023,
    reflection: null,
    photo: "/images/artifacts/always-loved-dancing.jpg",
  },
  {
    id: "deep-conversations",
    title: "Deep Conversations with Strangers",
    date: "November 17, 2023",
    period: "Sophomore Year",
    theme: "Consistent Curiosity",
    themeKey: "curiosity",
    year: 2023,
    reflection: null,
    photo: "/images/artifacts/deep-conversations.jpg",
  },
  {
    id: "open-endings",
    title: "Open Endings",
    date: "April 7–12, 2025",
    period: "Junior Year",
    theme: "Consistent Curiosity",
    themeKey: "curiosity",
    year: 2025,
    reflection: null,
    photo: "/images/artifacts/open-endings.jpg",
  },
  {
    id: "being-a-ta",
    title: "Being a TA",
    date: "January 2025 – June 2026",
    period: "Junior and Senior Year",
    theme: "Consistent Curiosity",
    themeKey: "curiosity",
    year: 2025,
    reflection: null,
    photo: "/images/artifacts/being-a-ta.jpg",
  },
  {
    id: "passion-in-project",
    title: "Passion in Project",
    date: "Winter 2026",
    period: "Senior Year",
    theme: "Consistent Curiosity",
    themeKey: "curiosity",
    year: 2026,
    reflection: null,
    photo: "/images/artifacts/passion-in-project.jpg",
  },
  // THEME 3: Relearning Authenticity
  {
    id: "lifes-philosophy",
    title: "Writing My Life's Philosophy at 18",
    date: "Winter 2023",
    period: "Freshman Year",
    theme: "Relearning Authenticity",
    themeKey: "authenticity",
    year: 2023,
    reflection: null,
    photo: "/images/artifacts/lifes-philosophy.jpg",
  },
  {
    id: "shrm",
    title: "SHRM",
    date: "Spring 2023",
    period: "Freshman Year",
    theme: "Relearning Authenticity",
    themeKey: "authenticity",
    year: 2023,
    reflection: null,
    photo: "/images/artifacts/shrm.jpg",
  },
  {
    id: "caseit-2024",
    title: "CaseIT 2024",
    date: "Winter 2024",
    period: "Sophomore Year",
    theme: "Relearning Authenticity",
    themeKey: "authenticity",
    year: 2024,
    reflection: null,
    photo: "/images/artifacts/caseit-2024.jpg",
  },
  {
    id: "lakeside-speaker",
    title: "Going Back to Lakeside as a Guest Speaker",
    date: "Summer 2025",
    period: "Junior Year",
    theme: "Relearning Authenticity",
    themeKey: "authenticity",
    year: 2025,
    reflection: null,
    photo: "/images/artifacts/lakeside-speaker.jpg",
  },
  {
    id: "first-solo-trip",
    title: "First Solo Trip",
    date: "Summer 2025",
    period: "Junior Year",
    theme: "Relearning Authenticity",
    themeKey: "authenticity",
    year: 2025,
    reflection: null,
    photo: "/images/artifacts/first-solo-trip.jpg",
  },
  {
    id: "husky-100",
    title: "Husky 100 Application",
    date: "Winter 2026",
    period: "Senior Year",
    theme: "Relearning Authenticity",
    themeKey: "authenticity",
    year: 2026,
    reflection: null,
    photo: "/images/artifacts/husky-100.jpg",
  },
];
